feat: switches database for ledger and ILP kit from sqlite to postgres
interledgerjs/five-bells-service-manager pull request #20
Opened 2017-03-17 16:01 UTC by dappelt

By changing the database used during integration test from sqlite to postgres, our integration test environment resembles more closely production environments (sqlite is not supported in production).

Furthermore, sqlite does not support concurrent access from different processes to the same database and some of the queries performed by ILP kit fail if sqlite is used.

2017-03-17 20:41 UTC, sentientwaffle requested changes
When I check out this branch, the integration tests fail (locally). I can fix it somewhat with
```
--- a/src/lib/seed-db.js
+++ b/src/lib/seed-db.js
@@ -34,7 +34,7 @@ function * setupAdminAccount (adminParams) {
       balance: '0',
       password_hash: passwordHash,
       is_admin: true,
-      minimum_allowed_balance: '-infinity',
+      minimum_allowed_balance: '0',
       fingerprint: adminParams.fingerprint
     })
   }
```
but even with that, it still fails intermittently.

2017-03-17 20:41 UTC, sentientwaffle commented on package.json
>      "sqlite": "^2.2.0",
If `sqlite` is no longer used it can be removed.

2017-03-20 12:57 UTC, dappelt commented
I cannot reproduce the behavior you are describing. When I am running the integration tests locally and I link `five-bells-service-manager` against this branch, all tests pass (29 passing, 2 pending).

It looks like you run the integration tests from the ledger repo. Did you pull the latest master? The function you are referring to contained indeed a bug that I fixed in PR interledgerjs/five-bells-ledger#404

2017-03-20 17:10 UTC, sentientwaffle approved these changes

2017-03-20 17:11 UTC, merged